name: Section 1

# Controls when the action will run.
on: workflow_dispatch

jobs:
  run-section-1:
    name: Section 1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler: 'latest'

      - name: Install Packages
        run: yarn install

      - name: Lint code
        run: yarn lint
      
      - name: Test code
        run: yarn test

      - name: Build code
        run: yarn build