name: Section 2

# Controls when the action will run.
on:
  issues:
    types: [opened, edited, milestoned]

jobs:
  run-section-1:
    name: Section 2
    runs-on: ubuntu-latest

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"